name: 'Syncpack: Synchronise monorepo dependency versions'
description: 'Always use the same versions of each dependency'

branding:
  icon: 'cloud-lightning'
  color: 'green'

inputs:
  bot-email:
    description: 'GitHub Email for the Syncpack Bot'
    required: false
    default: 'github-actions@github.com'
  bot-username:
    description: 'GitHub Username for the Syncpack Bot'
    required: false
    default: 'github-actions[bot]'
  commit-message:
    description: 'Commit Message to use when applying fixes'
    required: false
    default: 'chore(syncpack): format and sync package.json files'
  format-mismatches:
    description: '"fix" | "ignore"'
    required: false
    default: 'fix'
  lockfile-mismatches:
    description: '"fix" | "ignore"'
    required: false
    default: 'fix'
  package-manager-version:
    description: 'The Semver version of npm, yarn, or pnpm'
    required: false
    default: 'latest'
  package-manager:
    description: 'Possible values npm | yarn | pnpm'
    required: false
    default: 'npm'
  semver-range-mismatches:
    description: '"lint" | "fix" | "ignore"'
    required: false
    default: 'fix'
  syncpack-version:
    description: 'The Semver version of syncpack'
    required: false
    default: '7.2.1'
  version-mismatches:
    description: '"lint" | "fix" | "ignore"'
    required: false
    default: 'fix'
  branch:
    description: 'Name of branch to open'
    required: false
    default: ''
  base-branch:
    description: 'Name of branch to create pull request against'
    required: false     
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Init
      id: init
      shell: bash
      run: |
        if [ "${{ inputs.version-mismatches }}" = "fix" ] || [ "${{ inputs.format-mismatches }}" = "fix" ] || [ "${{ inputs.semver-range-mismatches }}" = "fix" ]; then
          echo "::set-output name=anyFixEnabled::true"
        fi

    - name: Install Syncpack
      id: install-syncpack
      shell: bash
      run: |
        npm i -g "syncpack@${{ inputs.syncpack-version }}"

    - if: ${{ steps.init.outputs.anyFixEnabled == 'true' && inputs.branch != '' }}
      name: Checkout Branch
      id: checkout-branch
      shell: bash
      run: |
        git config pull.rebase true
        git fetch
        git checkout $GITHUB_HEAD_REF
        git pull origin $GITHUB_HEAD_REF
    
    - if: ${{ inputs.branch != '' }}
      name: Create Branch
      id: create-branch
      shell: bash
      run: |
        git fetch
        git pull origin $GITHUB_HEAD_REF
        git checkout -b ${{ inputs.branch }}

    # Version Mismatches
    # https://github.com/zerodom30/syncpack#list-mismatches
    # https://github.com/zerodom30/syncpack#fix-mismatches

    - if: ${{ inputs.version-mismatches == 'fix' }}
      name: syncpack fix-mismatches
      id: version-mismatches-fix
      shell: bash
      run: |
        set +e
        value="$(syncpack fix-mismatches)"
        value="${value//'%'/'%25'}"
        value="${value//$'\n'/'%0A'}"
        value="${value//$'\r'/'%0D'}"
        echo "::set-output name=stdout::$value"
        set -e
        if [[ `git diff --name-only` ]]; then
          git add .
          echo "::set-output name=has-changes::true"
        fi

    # Format Mismatches
    # https://github.com/zerodom30/syncpack#format

    - if: ${{ inputs.format-mismatches == 'fix' }}
      name: syncpack format
      id: format-mismatches-fix
      shell: bash
      run: |
        set +e
        value="$(syncpack format)"
        value="${value//'%'/'%25'}"
        value="${value//$'\n'/'%0A'}"
        value="${value//$'\r'/'%0D'}"
        echo "::set-output name=stdout::$value"
        set -e
        if [[ `git diff --name-only` ]]; then
          git add .
          echo "::set-output name=has-changes::true"
        fi

    # Semver Range Mismatches
    # https://github.com/zerodom30/syncpack#lint-semver-ranges
    # https://github.com/zerodom30/syncpack#set-semver-ranges

    - if: ${{ inputs.semver-range-mismatches == 'fix' }}
      name: syncpack set-semver-ranges
      id: semver-range-mismatches-fix
      shell: bash
      run: |
        set +e
        value="$(syncpack set-semver-ranges)"
        value="${value//'%'/'%25'}"
        value="${value//$'\n'/'%0A'}"
        value="${value//$'\r'/'%0D'}"
        echo "::set-output name=stdout::$value"
        set -e
        if [[ `git diff --name-only` ]]; then
          git add .
          echo "::set-output name=has-changes::true"
        fi

    - if: ${{ inputs.lockfile-mismatches != 'ignore' }}
      name: Update Lockfile
      id: lockfile-mismatches-fix
      shell: bash
      run: |
        if [ "${{ inputs.package-manager }}" = "yarn" ]; then
          npm i -g "yarn@${{ inputs.package-manager-version }}"
          yarn install
        elif [ "${{ inputs.package-manager }}" = "pnpm" ]; then
          npm i -g "pnpm@${{ inputs.package-manager-version }}"
          pnpm install --no-frozen-lockfile
        else
          npm i -g "npm@${{ inputs.package-manager-version }}"
          npm install
        fi

    - if: ${{ steps.init.outputs.anyFixEnabled == 'true' }}
      name: Detect Changes
      id: detect-changes
      shell: bash
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "::set-output name=has-changes::true"
        fi

    - if: ${{ steps.init.outputs.anyFixEnabled == 'true' }}
      name: Commit and Push
      id: commit-and-push
      shell: bash
      run: |
        if [ "${{ steps.detect-changes.outputs.has-changes }}" = "true" ]; then
          git add .
          git config user.name "${{ inputs.bot-username }}"
          git config user.email "${{ inputs.bot-email }}"
          git commit -m "${{ inputs.commit-message }}"
          git push --set-upstream origin "${{ inputs.branch }}"
        fi

    - if: always()
      name: syncpack list-mismatches
      id: version-mismatches-lint
      shell: bash
      run: |
        if [ "${{ inputs.version-mismatches }}" = "lint" ]; then
          set +e
          value="$(syncpack list-mismatches)"
          value="${value//'%'/'%25'}"
          value="${value//$'\n'/'%0A'}"
          value="${value//$'\r'/'%0D'}"
          echo "::set-output name=stdout::$value"
          set -e
          syncpack list-mismatches
        fi

    - if: always()
      name: syncpack lint-semver-ranges
      id: semver-range-mismatches-lint
      shell: bash
      run: |
        if [ "${{ inputs.semver-range-mismatches }}" = "lint" ]; then
          set +e
          value="$(syncpack lint-semver-ranges)"
          value="${value//'%'/'%25'}"
          value="${value//$'\n'/'%0A'}"
          value="${value//$'\r'/'%0D'}"
          echo "::set-output name=stdout::$value"
          set -e
          syncpack lint-semver-ranges
        fi

    - if: always()
      name: Get Comment Body
      id: get-comment-body
      shell: bash
      run: |
        touch comment.txt
        if [ "${{ inputs.version-mismatches }}" = "lint" ]; then
          if [ "${{ steps.version-mismatches-lint.outcome }}" = "success" ]; then
            echo '```' >> comment.txt
            echo "$ syncpack list-mismatches" >> comment.txt
            echo "✓" >> comment.txt
            echo '```' >> comment.txt
            echo "" >> comment.txt
          fi
          if [ "${{ steps.version-mismatches-lint.outcome }}" = "failure" ]; then
            echo "" >> comment.txt
            echo '```' >> comment.txt
            echo "$ syncpack list-mismatches" >> comment.txt
            echo "${{ steps.version-mismatches-lint.outputs.stdout }}" >> comment.txt
            echo '```' >> comment.txt
            echo "" >> comment.txt
          fi
        fi
        if [ "${{ inputs.semver-range-mismatches }}" = "lint" ]; then
          if [ "${{ steps.semver-range-mismatches-lint.outcome }}" = "success" ]; then
            echo '```' >> comment.txt
            echo "$ syncpack lint-semver-ranges" >> comment.txt
            echo "✓" >> comment.txt
            echo '```' >> comment.txt
            echo "" >> comment.txt
          fi
          if [ "${{ steps.semver-range-mismatches-lint.outcome }}" = "failure" ]; then
            echo "" >> comment.txt
            echo '```' >> comment.txt
            echo "$ syncpack lint-semver-ranges" >> comment.txt
            echo "${{ steps.semver-range-mismatches-lint.outputs.stdout }}" >> comment.txt
            echo '```' >> comment.txt
            echo "" >> comment.txt
          fi
        fi
        if [ "${{ inputs.version-mismatches }}" = "fix" ]; then
          if [ "${{ steps.version-mismatches-fix.outputs.has-changes }}" = "true" ]; then
            echo "" >> comment.txt
            echo '```' >> comment.txt
            echo "$ syncpack fix-mismatches" >> comment.txt
            echo "${{ steps.version-mismatches-fix.outputs.stdout }}" >> comment.txt
            echo '```' >> comment.txt
            echo "" >> comment.txt
          fi
        fi
        if [ "${{ inputs.format-mismatches }}" = "fix" ]; then
          if [ "${{ steps.format-mismatches-fix.outputs.has-changes }}" = "true" ]; then
            echo "" >> comment.txt
            echo '```' >> comment.txt
            echo "$ syncpack format" >> comment.txt
            echo "${{ steps.format-mismatches-fix.outputs.stdout }}" >> comment.txt
            echo '```' >> comment.txt
            echo "" >> comment.txt
          fi
        fi
        if [ "${{ inputs.semver-range-mismatches }}" = "fix" ]; then
          if [ "${{ steps.semver-range-mismatches-fix.outputs.has-changes }}" = "true" ]; then
            echo "" >> comment.txt
            echo '```' >> comment.txt
            echo "$ syncpack set-semver-ranges" >> comment.txt
            echo "${{ steps.semver-range-mismatches-fix.outputs.stdout }}" >> comment.txt
            echo '```' >> comment.txt
            echo "" >> comment.txt
          fi
        fi
        body=$(cat comment.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}"
        echo "::set-output name=body::"$body""

    - if: ${{ inputs.branch != '' }}
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with: 
        base: ${{ inputs.base-branch }}
        reviewers: "zerodom30"
        branch: ${{ inputs.branch }}

    # - if: always()
    #   name: Find Comment
    #   id: find-comment
    #   uses: peter-evans/find-comment@v2
    #   with:
    #     issue-number: ${{ github.event.pull_request.number }}
    #     comment-author: ${{ inputs.bot-username }}
    #     body-includes: '<!-- syncpack-bot -->'

    # - if: always()
    #   name: Upsert Comment
    #   id: upsert-comment
    #   uses: peter-evans/create-or-update-comment@v2
    #   with:
    #     comment-id: ${{ steps.find-comment.outputs.comment-id }}
    #     issue-number: ${{ github.event.pull_request.number }}
    #     edit-mode: replace
    #     body: |
    #       Synchronise monorepo dependency versions with [`syncpack`](https://github.com/zerodom30/syncpack)
    #       ${{ steps.get-comment-body.outputs.body }}
    #       <!-- syncpack-bot -->
